# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'armpipelinetute'
    subscriptionId: '8d7b7d7d-4cef-4ff2-8a26-c2020c167519'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRMPipelineTute'
    location: 'Australia Southeast'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureRMPipelineTute -linkedTemplateUri https://raw.githubusercontent.com/Ayoore/AzureRmPipeline-repo/master/CreateWebApp/azuredeploy.linkedstorageacc.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'